### ISSUE TITLE
Assets!

### ISSUE THREAD

**Issue by voldikss** [voldikss/voldikss.github.io#1]
![ddd 3](https://user-images.githubusercontent.com/20282795/46467105-84004c00-c7ff-11e8-9e2e-e64b4a30fbaf.gif)

**Comment by VoldikSS** [comment]
Vim-mma
![vimmma](https://user-images.githubusercontent.com/20282795/46467204-bf027f80-c7ff-11e8-82c9-acf43f3b89e1.png)

**Comment by VoldikSS** [comment]
![Uploading 2.gif…]()

**Comment by VoldikSS** [comment]
![2mp4_20181020_085833](https://user-images.githubusercontent.com/20282795/47249513-b8eae080-d446-11e8-80b3-ca0f456cbc45.gif)

**Comment by voldikss** [comment]
![photo_2018-12-06_12-46-21](https://user-images.githubusercontent.com/20282795/49562085-02d74980-f955-11e8-9088-5f608994bad2.jpg)
![dsc_2555](https://user-images.githubusercontent.com/20282795/49562147-416d0400-f955-11e8-828b-2867e1a615f2.jpg)

**Comment by voldikss** [comment]
![1760771396](https://user-images.githubusercontent.com/20282795/62786670-a933aa00-baf5-11e9-9941-6d2551758faa.jpg)

**Comment by voldikss** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/20282795/78157412-82eec000-7472-11ea-88d9-1fe81ceed50b.jpeg)
